// flow-typed signature: a5323acaa5a1586bf85ec0de85941b7e
// flow-typed version: <<STUB>>/eth-query_v^2.1.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eth-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eth-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eth-query/index' {
  declare module.exports: $Exports<'eth-query'>;
}
declare module 'eth-query/index.js' {
  declare module.exports: $Exports<'eth-query'>;
}
