// flow-typed signature: a5405934cc67ca3f09fd3f0d7ec7afe4
// flow-typed version: <<STUB>>/web3-providers-http_v^1.0.0-beta.33/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-providers-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-providers-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-providers-http/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-providers-http/src/index.js' {
  declare module.exports: $Exports<'web3-providers-http/src/index'>;
}
